#!/bin/bash
# setup_github.sh - 快速配置 GitHub 仓库和自动打包

echo "=========================================="
echo "🚀 GitHub 自动打包配置向导"
echo "=========================================="
echo ""

# 检查是否已经是 Git 仓库
if [ ! -d ".git" ]; then
    echo "📝 初始化 Git 仓库..."
    git init
    git add .
    git commit -m "初始提交：艾伦方差分析工具"
    echo "✅ Git 仓库初始化完成"
else
    echo "✅ 已存在 Git 仓库"
fi

echo ""
echo "=========================================="
echo "📋 下一步操作指南"
echo "=========================================="
echo ""
echo "请按照以下步骤完成配置："
echo ""
echo "【步骤 1】创建 GitHub 仓库"
echo "  1. 访问: https://github.com/new"
echo "  2. 仓库名: allan_variance_tool"
echo "  3. 可见性: Public 或 Private"
echo "  4. 不要勾选任何初始化选项"
echo "  5. 点击 'Create repository'"
echo ""
echo "【步骤 2】关联远程仓库"
echo "  复制你的仓库地址，然后执行："
echo "  git remote add origin https://github.com/你的用户名/allan_variance_tool.git"
echo "  git branch -M main"
echo "  git push -u origin main"
echo ""
echo "【步骤 3】发布第一个版本"
echo "  执行:"
echo "  ./release.sh 1.0.0"
echo ""
echo "【步骤 4】查看打包进度"
echo "  访问你的仓库 → Actions 选项卡"
echo "  等待约 5-10 分钟"
echo ""
echo "【步骤 5】下载打包结果"
echo "  方式一: 仓库 → Actions → 下载 Artifacts"
echo "  方式二: 仓库 → Releases → 下载发布文件"
echo ""
echo "=========================================="
echo "💡 提示"
echo "=========================================="
echo ""
echo "每次发布新版本时，只需执行："
echo "  ./release.sh 版本号"
echo ""
echo "例如:"
echo "  ./release.sh 1.0.1"
echo "  ./release.sh 1.1.0"
echo "  ./release.sh 2.0.0"
echo ""
echo "GitHub Actions 会自动为你打包："
echo "  ✓ Windows 便携版 (.zip)"
echo "  ✓ macOS DMG 安装包 (.dmg)"
echo ""
echo "=========================================="
